{% set name = "jekyll-readme-index" %}
{% set version = "0.3.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: d74cc4de46b2d350229be7409495149e656a31fb5a5fe3fe6135dbf7435e1e32

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-jekyll >=3.0,<4

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A Jekyll plugin to render a project's README as the site's index.

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/benbalter/{{ name }}

extra:
  recipe-maintainers:
    - sodre
