travis:
  secure:
    BINSTAR_TOKEN: xByDqZKLBNSQf5+tp+Vcvd7DoR6PParanzId1uyXsbClTW2+yIbJlzvlAkOsJ2vaP3xEMHl+foL1ypI0bL3Q8H3/UfVJO8MN+iDmNMWkcku88y0ncjnWlhVNMVQGmiAomrgVeBUeSA2hnfTguJsy8ZWe/RxRRptLBsYjyTuNLPYu3CrPddIt9DAEcLkffCa8DiiY6ef47wmMXsmjsZrMyxNpf7d/L3bVVDbuH1BiRpV32ERixxiqLLhf69c0/VJoyduHimoMiFGdJYJcmrrsdPR3YHhO0s/CGzMnMTMnC4t7pfb1InBz/vwHZUsRiva+79kzAjiMXoUXnByX9PjDe4wvHGuqjckfwUsqaIcf5AW+wIIJ8RPRbMKMuSFMW/vGUpHTdY+PH6pWogIHfSBxgZXEVtricJbWDKuS6OIDWsVo2PRK7aCkM3Wy7gGWhOTQYR/E7jAKNuMem0uVCd9HMJ53s0JAQIs4ZarKQ92iIr7oEsqwu5txA9n6AngOjOJA65DkTLtB8XNInd4aKTNCOMIk5VxtXb96RqtFDbbe5HxqRT51m3UlLXasdaCnBqMXSIwbKOFXxge3xHo4+sgyoyg0zCqRpl9croM0vkIvpQckW/cnwMqr0UDpM2sIH1HMYf+T1dmX7Fioxqd4+/qHVhcsoPBQRjXhZtYzCVXwKrM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
